/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author ms
 */
public class KombPanel extends javax.swing.JPanel {

    /**
     * Creates new form KombPanel
     */
    JTable guiJTable = new JTable();
    
    public KombPanel() {
        initComponents();
        
        guiJTable = gui_kTab;
    }
    
    void refresh(){
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        consoleText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        gui_kTab = new javax.swing.JTable();
        gui_kSP = new javax.swing.JSlider();

        consoleText.setColumns(20);
        consoleText.setRows(5);
        jScrollPane1.setViewportView(consoleText);

        gui_kTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G", "H", "I", ""
            }
        ));
        gui_kTab.setName("k_tab"); // NOI18N
        jScrollPane2.setViewportView(gui_kTab);

        gui_kSP.setMaximum(10);
        gui_kSP.setMinimum(4);
        gui_kSP.setMinorTickSpacing(1);
        gui_kSP.setPaintLabels(true);
        gui_kSP.setPaintTicks(true);
        gui_kSP.setSnapToTicks(true);
        gui_kSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gui_kSPMouseReleased(evt);
            }
        });
        gui_kSP.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                gui_kSPStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gui_kSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(gui_kSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gui_kSPMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gui_kSPMouseReleased
        
        DefaultTableModel dtm = (DefaultTableModel) gui_kTab.getModel();
        dtm.setColumnCount(gui_kSP.getValue());
        dtm.setRowCount(gui_kSP.getValue());
        guiJTable.setModel(dtm);
        
        //gui_kTab.setModel(dtm);
        //gui_kTab.
    }//GEN-LAST:event_gui_kSPMouseReleased

    private void gui_kSPStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_gui_kSPStateChanged
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) gui_kTab.getModel();
        dtm.setColumnCount(gui_kSP.getValue());
        dtm.setRowCount(gui_kSP.getValue());
        gui_kTab.setModel(dtm);
        
    }//GEN-LAST:event_gui_kSPStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea consoleText;
    private javax.swing.JSlider gui_kSP;
    private javax.swing.JTable gui_kTab;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void printLine(String txt) {
        consoleText.append(txt + "\n");
    }
}
